repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff
        types_or: [python, pyi]
        args: [--fix]
        files: ^synthlearners/
      - id: ruff-format
        types_or: [python, pyi]
        files: ^synthlearners/
