repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: pixi run -e lint ruff check --fix --exit-non-zero-on-fix --force-exclude
        language: system
        types_or: [python]
        require_serial: true
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
