repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
      - id: ruff
        entry: ruff
        name: ruff
        language: system
        types_or: [python, pyi]
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        name: fmt
        entry: ruff-format
        types_or: [python, pyi]
        language: system
